### ISSUE TITLE
Release build does not find misspellings, debug build does

### ISSUE THREAD

**Issue by snomos** [roguePanda/MacVoikko#6]
To repeat:
1. Open the project in XCode
2. build a debug version using XCode (Cmd-B in XCode)
3. install
4. test some text, e.g. "Tämä ja tämää muttta ei näämä" (the third, fourth and last words are misspelled), and check that you get red underlines
5. uninstall, and rebuild as release (I have been using the Instrument build, and just quitting Instruments as soon as it pops up)
6. install the release build
7. notice that there are no red underlines

NB! I tested using a zhfst file, not the Finnish Malaga-based speller above. There might be differences between the two.

Other observations:

Based on the log output, it seems that the release version never traverses the input string to find misspellings. I inserted a couple of extra log statements, and found several interesting things:

* the issue seems to be located in VoikkoSpellChecker.m, function `spellServer: findMisspelledWordInString: language: wordCount: countOnly: `
* the word count is constant: 140734693119360 (debug build)/140734631319008 (release build) - this looks more like a pointer value than an actual word count
* the if statement `if(countOnly)` only evaluates to true in the debug version, not in the release version

**Comment by roguePanda** [comment]
I think there was a bug in the CocoaVoikko.m function `enumerateTokens: withBlock` method where the `tokenType` variable was initialized as `TOKEN_NONE` in release builds but not debug ones. Maybe something about zeroing uninitialized variables? Changing the while loop to a do-while seems to work for both builds. The word count variable passed in is a pointer to an integer since the method can't return the misspelled word range and the word count.
